services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: cleanurl-dynamodb
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    volumes:
      - "./data:/home/dynamodblocal/data"